In [2]:
import numpy as np

In [12]:
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# get dimension
a.ndim

1

In [10]:
# get shame
b.shape

(2, 3)

In [13]:
# get type
a.dtype

dtype('int16')

In [14]:
a.itemsize

2

In [15]:
# get total size
a.size * a.itemsize

6

In [17]:
# or
a.nbytes

6

In [18]:
b.itemsize

8

In [25]:
new_a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(new_a.shape)

(2, 7)


In [27]:
new_a.ndim

2

In [28]:
print(new_a[1][5])
print(new_a[1, 5])

13
13


In [34]:
# selecting specific row
new_a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# selecting specific column
new_a[:, 3]

array([ 4, 11])

In [45]:
# [startIndex:endIndex:step]
new_a[0, 1:5:2]

array([2, 4])

In [46]:
# change values of matrix
print(new_a[0, 5])
new_a[0, 5] = 50
print(new_a[0, 5])

6
50


In [48]:
# change multiple values
print(new_a[:, 1:4])
new_a[:, 1:4] = 100
print(new_a[:, 1:4])

[[ 2  3  4]
 [ 9 10 11]]
[[100 100 100]
 [100 100 100]]


In [51]:
# change multiple values with array
print("old array", new_a[0,0:2])
new_a[0,0:2] = [400, 600]
print("new array", new_a[0,0:2])

old array [200 300]
new array [400 600]


In [ ]:
# Different Types of arrays

In [53]:
# all 0s matrix
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# all 1s matrix
np.ones((2, 2), dtype='int32')

array([[1, 1],
       [1, 1]])

In [56]:
# any other numbers
np.full((4, 4), 55)

array([[55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55]])

In [58]:
np.full(new_a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [59]:
# random decimal numbers
np.random.rand(4, 4)

array([[0.12694361, 0.21496356, 0.13563008, 0.47335329],
       [0.91751652, 0.4098153 , 0.95575892, 0.22984633],
       [0.17824141, 0.99323071, 0.94689246, 0.81685405],
       [0.80347795, 0.36810301, 0.4255963 , 0.36949232]])

In [60]:
np.random.rand(*new_a.shape)

array([[0.19408984, 0.87332003, 0.74967224, 0.31144202, 0.04193921,
        0.74756199, 0.42356465],
       [0.59808821, 0.12852369, 0.7115354 , 0.43932484, 0.92469059,
        0.55283222, 0.79760151]])

In [61]:
# random integer values
np.random.randint(10, size=(3, 3))

array([[5, 8, 2],
       [8, 4, 5],
       [8, 8, 2]])

In [105]:
np.random.rand(3, 3)*10

array([[6.57401945, 6.59139449, 5.26731537],
       [8.0020384 , 5.19829291, 0.89928322],
       [5.22626121, 7.40693634, 7.59168462]])

In [92]:
np.random.randint(7,10, size=(3, 3))
#                include 7 and exclude 10

array([[7, 9, 8],
       [9, 9, 8],
       [7, 7, 9]])

In [93]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [102]:
# repeat an array with y axis
arr = np.array([[1,2,3],[10,20,30]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[ 1  2  3]
 [ 1  2  3]
 [ 1  2  3]
 [10 20 30]
 [10 20 30]
 [10 20 30]]


In [104]:
# repeat an array with x axis
arr = np.array([[1,2],[10,20]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[ 1  1  1  2  2  2]
 [10 10 10 20 20 20]]


In [7]:
a = np.ones((5, 5), dtype="int32")
a[1:-1, 1:-1] = 0
a[2, 2] = 9

print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


careful for copying arrays

In [8]:
print(id(a))
b = a
print(id(b))

1970531085648
1970531085648


In [9]:
print(id(a))
c = a.copy()
print(id(c))

1970531085648
1970531083168


In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.cos(a) ** 2 + np.sin(a) ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.dot(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [16]:
np.dot(a, 6)

array([[6., 6., 6.],
       [6., 6., 6.]])