# Numpy
___

[![Numpy image](http://img.youtube.com/vi/NVTWjd_UpzM/0.jpg)](http://www.youtube.com/watch?v=NVTWjd_UpzM "Numpy Playlist")


**Numpy features**
___
1. sorting data
2. mutable iterable object
3. can be indexed
4. slicing operation can be perform

**diff between list and numpy array**
____
list = different datatypes (e.g. [1,'a',3])

np.array = similar datatypes (e.g. [1, 2, 3])

In [1]:
import numpy as np

Numpy operation
___
* array()

* arange()

* zeros()

* ones()

* linspace()

* eye()

* random()

### array

In [84]:
myList = [10, 55, 16, 74, 98]
np.array(myList)

array([10, 55, 16, 74, 98])

In [86]:
myList = [10, 55, 16, 74, 98, 26]
np.array(myList).reshape(2, -1)

array([[10, 55, 16],
       [74, 98, 26]])

In [87]:
myList = [10, 55, 16, 74, 98, 26]
np.array(myList).reshape(2, 3)

array([[10, 55, 16],
       [74, 98, 26]])

### arange
___
numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray
___
**numpy integer datatypes**


* np.int8: 8-bit signed integer (from -128 to 127)

* np.uint8: 8-bit unsigned integer (from 0 to 255)

* np.int16: 16-bit signed integer (from -32768 to 32767)

* np.uint16: 16-bit unsigned integer (from 0 to 65535)

* np.int32: 32-bit signed integer (from -2 ** 31 to 2 ** 31-1)

* np.uint32: 32-bit unsigned integer (from 0 to 2** 32-1)

* np.int64: 64-bit signed integer (from -2** 63 to 2** 63-1)

* np.uint64: 64-bit unsigned integer (from 0 to 2** 64-1)

In [26]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [30]:
np.arange(10, dtype='uint8')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

![image](https://files.realpython.com/media/fig-1.1d8bc9379e87.png)

In [41]:
x = np.arange(1, 5)
x.size * x.itemsize

16

In [39]:
x**2

array([ 1,  4,  9, 16], dtype=int32)

In [43]:
x = x.astype('uint8')
x.size * x.itemsize

4

In [65]:
a = np.arange(6).reshape((2, 3))
print(f'\
Shape = {a.shape}\n\
dimension = {a.ndim}\n\
total number of elements = {a.size}\n\
each element size = {a.itemsize}\n\
total size consumed by array = {a.nbytes}')

Shape = (2, 3)
dimension = 2
total number of elements = 6
each element size = 4
total size consumed by array = 24


In [75]:
np.arange(-1, 1.1, 0.5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [76]:
np.abs(np.arange(-1, 1.1, 0.5))

array([1. , 0.5, 0. , 0.5, 1. ])

In [77]:
np.sin(np.arange(0, 180, 15))

array([ 0.        ,  0.65028784, -0.98803162,  0.85090352, -0.30481062,
       -0.38778164,  0.89399666, -0.97053528,  0.58061118,  0.08836869,
       -0.71487643,  0.99779728])

In [81]:
%%timeit
np.arange(10)

610 ns ± 17.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [82]:
%%timeit
[x for x in range(10)]

654 ns ± 55.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [83]:
np.arange(8, 2)

array([], dtype=int32)

### zeros
___
```python
numpy.zeros(shape, dtype = None, order = 'C')
```
___

shape : integer or sequence of integers

order  : C_contiguous or F_contiguous

         C-contiguous order in memory(last index varies the fastest)
         
         C order means that operating row-rise on the array will be slightly quicker
         
         FORTRAN-contiguous order in memory (first index varies the fastest).
         
         F order means that column-wise operations will be faster. 
         
dtype : [optional, float(byDeafult)] Data type of returned array. 

In [66]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
np.zeros(4, dtype='int8')

array([0, 0, 0, 0], dtype=int8)

### ones
___
```python
numpy.ones(shape, dtype = None, order = 'C')
```
___

shape : integer or sequence of integers

order  : C_contiguous or F_contiguous

         C-contiguous order in memory(last index varies the fastest)
         
         C order means that operating row-rise on the array will be slightly quicker
         
         FORTRAN-contiguous order in memory (first index varies the fastest).
         
         F order means that column-wise operations will be faster. 
         
dtype : [optional, float(byDeafult)] Data type of returned array. 

In [68]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
np.ones(7, dtype='int')

array([1, 1, 1, 1, 1, 1, 1])

In [70]:
np.ones((3, 4), dtype='uint8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [72]:
np.full((3, 4), 69)

array([[69, 69, 69, 69],
       [69, 69, 69, 69],
       [69, 69, 69, 69]])

In [73]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [74]:
np.empty((3, 4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### linspace
___

**creates array filled evenly spaced values**
___
```
numpy.linspace(start,
               stop,
               num = 50,
               endpoint = True,
               retstep = False,
               dtype = None)
```
___
```
-> start  : [optional] start of interval range. By default start = 0
-> stop   : end of interval range
-> restep : If True, return (samples, step). By deflut restep = False
-> num    : [int, optional] No. of samples to generate
-> dtype  : type of output array
```