## NumPy Tutorial: Your First Steps Into Data Science in Python
___
[website link](https://realpython.com/numpy-tutorial/)

In [1]:
import pandas as pd
import numpy as np

In [2]:
>>> CURVE_CENTER = 80
>>> grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
>>> def curve(grades):
...     average = grades.mean()
...     change = CURVE_CENTER - average
...     new_grades = grades + change
...     return np.clip(new_grades, grades, 100)

In [3]:
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [4]:
temperatures = np.array([
   ...:     29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
   ...:     12.6, 49.9, 38.6, 31.3, 9.2, 22.2
   ...: ]).reshape(2, 2, 3)
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [5]:
temperatures.shape

(2, 2, 3)

In [6]:
np.swapaxes(temperatures, 1, 2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

In [7]:
type(temperatures)

numpy.ndarray

In [8]:
np.swapaxes(temperatures, 0, 2)

array([[[29.3, 12.6],
        [16.1, 31.3]],

       [[42.1, 49.9],
        [38. ,  9.2]],

       [[18.8, 38.6],
        [12.5, 22.2]]])

In [9]:
temperatures.max()

49.9

In [10]:
table = np.array([
   ...:     [5, 3, 7, 1],
   ...:     [2, 6, 7 ,9],
   ...:     [1, 1, 1, 1],
   ...:     [4, 3, 2, 0],
   ...: ])

In [11]:
table.max()

9

## Broadcasting
___

**broadcasting rules:**

1. size of each dimension should be same
2. size of one of the dimension should be 1

___
**Explained**

* if two numpy arrays differ in their no of dim, then the shape of the one with fewer(low) dim is padded with 1(s) on its leading side(left most side).

* If the shape is the two numpy arrays does not match in any dimension, the array with shapw equal to 1 in that dimension is streached to match the other shape.

* If both of the rules did not apply then it will throw ValueError
___


In [12]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3, 4])

In [13]:
a.shape

(3,)

In [14]:
b.shape

(4,)

In [15]:
# 3!= 4 so error
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [16]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([1,2])

In [17]:
a.shape

(3, 2)

In [18]:
b.shape

(2,)

```python
a.shape = (3, 2) = (3, 2)
b.shape = (2,)   = (1, 2) #rule 1
# a.shape[1] == b.shape[1]
```

In [19]:
a+b

array([[2, 4],
       [4, 6],
       [6, 8]])

In [20]:
a = np.array([[1],[2],[3]])
b = np.array([10, 20, 30])

In [21]:
a.shape

(3, 1)

In [22]:
b.shape

(3,)

```python
a.shape = (3, 1) = (3, 1)
b.shape = (3,)   = (1, 3) #rule 1
# a.shape[1] != b.shape[1]
# but b.shape cointain 1 on left most side
```

In [23]:
a + b 

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [24]:
A = np.arange(32).reshape(4, 1, 8)
A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [25]:
B = np.arange(48).reshape(1, 6, 8)
B

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [28]:
C = A + B
C

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

In [29]:
C.shape

(4, 6, 8)

In [31]:
x1 = np.linspace(0, 2, 15)

In [32]:
x1

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [33]:
x1 = np.linspace(0, 2, 15, endpoint = True)
x1

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [34]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)
# array.reshape() can take -1 as one of its dimension sizes.
# That signifies that NumPy should just figure out how big that particular axis needs to be based on the size of the other axes.
numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [35]:
mask = (numbers % 4 == 0) #vectorized Boolean computation
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [36]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [38]:
from numpy.random import default_rng

rng = default_rng()
values = rng.standard_normal(10)
values

array([-1.05680118,  0.65318948,  0.89898588,  1.3324819 ,  1.18946837,
        1.3193103 , -0.88618299, -1.5313588 , -0.1165946 , -0.0720914 ])

In [39]:
a = np.array([
   ...:     [1, 2],
   ...:     [3, 4],
   ...:     [5, 6],
   ...: ])

In [40]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [41]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [42]:
data = np.array([
   ...:     [7, 1, 4],
   ...:     [8, 6, 5],
   ...:     [1, 2, 3]
   ...: ])

In [44]:
data.sort()
data

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [45]:
np.sort(data)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [46]:
np.sort(data, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
np.sort(data, axis=1)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [48]:
np.sort(data, axis=0)

array([[1, 2, 3],
       [1, 4, 7],
       [5, 6, 8]])

In [49]:
a = np.array([
   ...:     [4, 8],
   ...:     [6, 1]
   ...: ])
b = np.array([
   ...:     [3, 5],
   ...:     [7, 2],
   ...: ])

In [50]:
np.hstack((a, b))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [52]:
np.vstack((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [53]:
np.concatenate((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [54]:
np.concatenate((a, b), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'