## NumPy Tutorial: Your First Steps Into Data Science in Python
___
[website link](https://realpython.com/numpy-tutorial/)

In [2]:
import pandas as pd
import numpy as np

In [3]:
>>> CURVE_CENTER = 80
>>> grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
>>> def curve(grades):
...     average = grades.mean()
...     change = CURVE_CENTER - average
...     new_grades = grades + change
...     return np.clip(new_grades, grades, 100)

In [4]:
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [5]:
temperatures = np.array([
   ...:     29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
   ...:     12.6, 49.9, 38.6, 31.3, 9.2, 22.2
   ...: ]).reshape(2, 2, 3)
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [6]:
temperatures.shape

(2, 2, 3)

In [7]:
np.swapaxes(temperatures, 1, 2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

In [8]:
type(temperatures)

numpy.ndarray

In [9]:
np.swapaxes(temperatures, 0, 2)

array([[[29.3, 12.6],
        [16.1, 31.3]],

       [[42.1, 49.9],
        [38. ,  9.2]],

       [[18.8, 38.6],
        [12.5, 22.2]]])

In [10]:
temperatures.max()

49.9

In [11]:
table = np.array([
   ...:     [5, 3, 7, 1],
   ...:     [2, 6, 7 ,9],
   ...:     [1, 1, 1, 1],
   ...:     [4, 3, 2, 0],
   ...: ])

In [12]:
table.max()

9

## Broadcasting
___

**broadcasting rules:**

1. size of each dimension should be same
2. size of one of the dimension should be 1

___
**Explained**

* if two numpy arrays differ in their no of dim, then the shape of the one with fewer(low) dim is padded with 1(s) on its leading side(left most side).

* If the shape is the two numpy arrays does not match in any dimension, the array with shapw equal to 1 in that dimension is streached to match the other shape.

* If both of the rules did not apply then it will throw ValueError
___


In [13]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3, 4])

In [14]:
a.shape

(3,)

In [15]:
b.shape

(4,)

In [16]:
# 3!= 4 so error
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [17]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([1,2])

In [18]:
a.shape

(3, 2)

In [19]:
b.shape

(2,)

```python
a.shape = (3, 2) = (3, 2)
b.shape = (2,)   = (1, 2) #rule 1
# a.shape[1] == b.shape[1]
```

In [20]:
a+b

array([[2, 4],
       [4, 6],
       [6, 8]])

In [21]:
a = np.array([[1],[2],[3]])
b = np.array([10, 20, 30])

In [22]:
a.shape

(3, 1)

In [23]:
b.shape

(3,)

```python
a.shape = (3, 1) = (3, 1)
b.shape = (3,)   = (1, 3) #rule 1
# a.shape[1] != b.shape[1]
# but b.shape cointain 1 on left most side
```

In [24]:
a + b 

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [25]:
A = np.arange(32).reshape(4, 1, 8)
A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [26]:
B = np.arange(48).reshape(1, 6, 8)
B

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [27]:
C = A + B
C

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

In [28]:
C.shape

(4, 6, 8)

In [29]:
x1 = np.linspace(0, 2, 15)

In [30]:
x1

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [31]:
x1 = np.linspace(0, 2, 15, endpoint = True)
x1

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [32]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)
# array.reshape() can take -1 as one of its dimension sizes.
# That signifies that NumPy should just figure out how big that particular axis needs to be based on the size of the other axes.
numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [33]:
mask = (numbers % 4 == 0) #vectorized Boolean computation
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [34]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [35]:
from numpy.random import default_rng

rng = default_rng()
values = rng.standard_normal(10)
values

array([ 1.35172837, -0.30947699,  1.03859797, -1.28115067, -1.14719069,
       -0.78919672,  1.28624448,  0.24114661,  0.4078878 ,  0.10439275])

In [36]:
a = np.array([
   ...:     [1, 2],
   ...:     [3, 4],
   ...:     [5, 6],
   ...: ])

In [37]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [38]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [39]:
data = np.array([
   ...:     [7, 1, 4],
   ...:     [8, 6, 5],
   ...:     [1, 2, 3]
   ...: ])

In [40]:
data.sort()
data

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [41]:
np.sort(data)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [42]:
np.sort(data, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
np.sort(data, axis=1)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [44]:
np.sort(data, axis=0)

array([[1, 2, 3],
       [1, 4, 7],
       [5, 6, 8]])

In [45]:
a = np.array([
   ...:     [4, 8],
   ...:     [6, 1]
   ...: ])
b = np.array([
   ...:     [3, 5],
   ...:     [7, 2],
   ...: ])

In [46]:
np.hstack((a, b))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [47]:
np.vstack((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [48]:
np.concatenate((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [49]:
np.concatenate((a, b), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

In [50]:
from math import e, factorial


fac = np.vectorize(factorial)

def e_x(x, terms=10):
    """Approximates e^x using a given number of terms of
    the Maclaurin series
    """
    n = np.arange(terms)
    return np.sum((x ** n) / fac(n))

if __name__ == "__main__":
    print("Actual:", e ** 3)  # Using e from the standard library

    print("N (terms)\tMaclaurin\tError")

    for n in range(1, 14):
        maclaurin = e_x(3, terms=n)
        print(f"{n}\t\t{maclaurin:.03f}\t\t{e**3 - maclaurin:.03f}")

Actual: 20.085536923187664
N (terms)	Maclaurin	Error
1		1.000		19.086
2		4.000		16.086
3		8.500		11.586
4		13.000		7.086
5		16.375		3.711
6		18.400		1.686
7		19.412		0.673
8		19.846		0.239
9		20.009		0.076
10		20.063		0.022
11		20.080		0.006
12		20.084		0.001
13		20.085		0.000
