## NumPy Tutorial: Your First Steps Into Data Science in Python
___
[website link](https://realpython.com/numpy-tutorial/)

In [1]:
import pandas as pd
import numpy as np

In [2]:
>>> CURVE_CENTER = 80
>>> grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
>>> def curve(grades):
...     average = grades.mean()
...     change = CURVE_CENTER - average
...     new_grades = grades + change
...     return np.clip(new_grades, grades, 100)

In [3]:
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [4]:
temperatures = np.array([
   ...:     29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
   ...:     12.6, 49.9, 38.6, 31.3, 9.2, 22.2
   ...: ]).reshape(2, 2, 3)
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [5]:
temperatures.shape

(2, 2, 3)

In [6]:
np.swapaxes(temperatures, 1, 2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

In [7]:
type(temperatures)

numpy.ndarray

In [8]:
np.swapaxes(temperatures, 0, 2)

array([[[29.3, 12.6],
        [16.1, 31.3]],

       [[42.1, 49.9],
        [38. ,  9.2]],

       [[18.8, 38.6],
        [12.5, 22.2]]])

In [9]:
temperatures.max()

49.9

In [13]:
table = np.array([
   ...:     [5, 3, 7, 1],
   ...:     [2, 6, 7 ,9],
   ...:     [1, 1, 1, 1],
   ...:     [4, 3, 2, 0],
   ...: ])

In [14]:
table.max()

9