> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [11]:
import jovian

In [12]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "iamkaushik2014/numpy-array-operations"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ikaushikpal/numpy-array-operations


'https://jovian.ai/ikaushikpal/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [3]:
# List of functions explained 
function1 = np.linalg.inv
function2 = np.transpose
function3 = np.append
function4 = np.linalg.norm
function5 = np.swapaxes

## Function 1 - np.linalg.inv

Add some explanation about the function in your own words

In [6]:
# Example 1 - working (change this)
mat1 = np.arange(1, 10).reshape(3, 3)
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Explanation about example

In [7]:
# Example 2 - working
np.linalg.inv(mat1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

Explanation about example

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
mat2 = np.arange(1, 7).reshape(2, 3)
mat2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.linalg.inv(mat2) 
# np.linalg.inv can only be used in only square matrix
# because mat2's shape(m, n) is 2, 3; and m != n so LinAlgError

LinAlgError: Last 2 dimensions of the array must be square

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ikaushikpal/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ikaushikpal/numpy-array-operations


'https://jovian.ai/ikaushikpal/numpy-array-operations'

## Function 2 - np.transpose

Add some explanations

In [14]:
# Example 1 - working
mat1 = np.array([1, 2, 3, 4, 5])
print(mat1.shape)

np.transpose(mat1)

(5,)


array([1, 2, 3, 4, 5])

Explanation about example

In [15]:
# Example 2 - working
mat2 = np.arange(1, 7).reshape(2, 3)
print(mat2.shape)

np.transpose(mat2)

(2, 3)


array([[1, 4],
       [2, 5],
       [3, 6]])

Explanation about example

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
mat3 = np.array([[1, 2, 3],[10, 20]])
# np.transpose(mat3)

np.transpose(mat3)
# which is not right because mat3 is not a proper 2D array
# first row of mat3 have 3 elements and 2nd row have only 2
# so mat3[1, 2] is not available

# np.transpose will work on any vector, matrix or nth dimentional numpy array

<ipython-input-22-307d13efd60f>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mat3 = np.array([[1, 2, 3],[10, 20]])


array([list([1, 2, 3]), list([10, 20])], dtype=object)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ikaushikpal/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ikaushikpal/numpy-array-operations


'https://jovian.ai/ikaushikpal/numpy-array-operations'

## Function 3 - np.append

Add some explanations

In [28]:
# Example 1 - working
mat1 = np.arange(1, 10).reshape(3, -1)
print(mat1.shape)

val = [10, 11, 12]
np.append(mat1,[val], axis=0)

(3, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Explanation about example

In [31]:
# Example 2 - working
mat2 = np.arange(1, 10).reshape(3, -1)
print(mat2.shape)

val = np.array([10, 11, 12]).reshape(3, 1)
np.append(mat2,val, axis=1)

(3, 3)


array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

Explanation about example

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
mat2 = np.arange(1, 10).reshape(3, -1)
print(mat2.shape)

val = np.array([10, 11]).reshape(2, 1)
np.append(mat2,val, axis=1)

# it will generate ValueError because val is 2D vector and mat2 is 3x3 matrix
# to append value at side of the mat2 val should be 3D vector 

(3, 3)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [34]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ikaushikpal/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ikaushikpal/numpy-array-operations


'https://jovian.ai/ikaushikpal/numpy-array-operations'

## Function 4 - np.linalg.norm

Add some explanations

In [37]:
# Example 1 - working
vec1 = np.array([1,2, 3])
np.linalg.norm(vec1)

3.7416573867739413

Explanation about example

In [38]:
# Example 2 - working
vec2 = np.array([1,2,3,4,5,6,7,9])
np.linalg.norm(vec2)

14.866068747318506

Explanation about example

In [43]:
# Example 3 - breaking (to illustrate when it breaks)


14.2828568570857

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [63]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ikaushikpal/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ikaushikpal/numpy-array-operations


'https://jovian.ai/ikaushikpal/numpy-array-operations'

## Function 5 - np.swapaxes

Add some explanations

In [64]:
# Example 1 - working
mat1 = np.arange(1, 10).reshape(3, 3)
np.swapaxes(mat1, 0, 1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Explanation about example

In [65]:
# Example 2 - working
mat2 = np.arange(1, 9).reshape(2, 2, 2)
np.swapaxes(mat2, 2, 0)

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [68]:
np.swapaxes(np.arange(1, 5), 1, 0)

AxisError: axis1: axis 1 is out of bounds for array of dimension 1

Explanation about example

In [71]:
# Example 3 - breaking (to illustrate when it breaks)
mat3 = np.arange(1, 10)
print(mat3.ndim)

np.swapaxes(mat3, 1, 0)
# mat3 is a nth dim vector and mat3 have only 1 axis
# so thats why if we try to swapaxes of mat3 there will be error
# swapaxes will work on 2d numpy array or more dim

1


AxisError: axis1: axis 1 is out of bounds for array of dimension 1

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [72]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ikaushikpal/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ikaushikpal/numpy-array-operations


'https://jovian.ai/ikaushikpal/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [73]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ikaushikpal/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ikaushikpal/numpy-array-operations


'https://jovian.ai/ikaushikpal/numpy-array-operations'